#!/usr/bin/env python
#  Copyright 2026 The CUINT Authors
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.

"""Generate boys_table.h: degree-7 Chebyshev interpolants of the Boys
function F_m(x) on 0.2-wide intervals over [0, 36), for m = 0..M_MAX.

Coefficients are stored in the monomial basis of u = (x - center) / (h/2),
u in [-1, 1], so the kernel evaluates them with a plain Horner chain.
Reference values come from mpmath at 50 digits; the fitted double-precision
polynomials are verified against the reference on a dense grid.
"""

import numpy as np
import mpmath

mpmath.mp.dps = 50

M_MAX = 20
H = 0.2
X_MAX = 35.0
N_INTERVALS = int(round(X_MAX / H))
DEGREE = 7

VERIFY = True

def boys(m, x):
    """F_m(x) = int_0^1 t^{2m} exp(-x t^2) dt to 50 digits."""
    if x == 0:
        return mpmath.mpf(1) / (2 * m + 1)
    x = mpmath.mpf(x)
    # F_m(x) = gamma_lower(m + 1/2, x) / (2 x^{m + 1/2})
    return mpmath.gammainc(m + mpmath.mpf(1) / 2, 0, x) / (
        2 * x ** (m + mpmath.mpf(1) / 2)
    )

# degree-7 interpolation at Chebyshev nodes of each interval
nodes_u = np.cos((2 * np.arange(DEGREE + 1) + 1) * np.pi / (2 * (DEGREE + 1)))
vander = np.vander(nodes_u, DEGREE + 1, increasing=True)

table = np.empty((M_MAX + 1, N_INTERVALS, DEGREE + 1))
for m in range(M_MAX + 1):
    for i in range(N_INTERVALS):
        center = (i + 0.5) * H
        values = np.array(
            [float(boys(m, center + 0.5 * H * u)) for u in nodes_u]
        )
        table[m, i] = np.linalg.solve(vander, values)

if VERIFY:
    # verify the double-precision Horner evaluation against mpmath
    max_rel = 0.0
    max_abs = 0.0
    rng = np.random.RandomState(0)
    for m in range(0, M_MAX+1):
        for x in rng.uniform(0.0, X_MAX, 400):
            i = min(int(x / H), N_INTERVALS - 1)
            u = (x - (i + 0.5) * H) * (2.0 / H)
            c = table[m, i]
            value = c[DEGREE]
            for k in range(DEGREE - 1, -1, -1):
                value = value * u + c[k]
            ref = float(boys(m, x))
            max_rel = max(max_rel, abs(value - ref) / ref)
            max_abs = max(max_abs, abs(value - ref))
    print(f"max relative error over verification grid: {max_rel:.3e}")
    print(f"max absolute error over verification grid: {max_abs:.3e}")
    assert max_rel < 1e-14

with open("boys_table.h", "w") as f:
    f.write("#pragma once\n\n")
    f.write("// generated by gen_boys_table.py -- do not edit\n")
    f.write(
        "// degree-7 Chebyshev interpolants of the Boys function F_m(x) in\n"
        "// the monomial basis of u = (x - center) / (h/2); layout\n"
        "// [m][interval][coefficient]\n\n"
    )
    f.write(f"#define BOYS_TABLE_M_MAX {M_MAX}\n")
    f.write(f"#define BOYS_N_INTERVALS {N_INTERVALS}\n")
    f.write(f"#define BOYS_INTERVAL_H {H}\n")
    f.write(f"#define BOYS_INTERVAL_INV_H {1.0/H}\n")
    f.write(f"#define BOYS_SWITCH_X {X_MAX}\n\n")
    f.write(
        "static __device__ const double boys_table"
        f"[{(M_MAX + 1) * N_INTERVALS * (DEGREE + 1)}] = {{\n"
    )
    flat = table.reshape(-1)
    for start in range(0, flat.size, 4):
        chunk = ", ".join(f"{v:.17e}" for v in flat[start : start + 4])
        f.write(f"    {chunk},\n")
    f.write("};\n")
print(f"boys_table.h written: {(M_MAX + 1) * N_INTERVALS * (DEGREE + 1) * 8 / 1024:.0f} KB")
